-------------------------------------------------------------------------------
--
--  ALICE - Adventures for Learning and Inspiring Coding Excellence
--  Copyright (c) 2023 Francesc Rocher <francesc.rocher@gmail.com>
--  SPDX-License-Identifier: MIT
--
--  ---------------------------------------------------------------------------
--
--  The following problem is taken from Project Euler:
--
--                 https://projecteuler.net/problem=12
--
--  Highly divisible triangular number
--  ----------------------------------
--
--  The sequence of triangle numbers is generated by adding the natural
--  numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
--  28. The first ten terms would be:
--
--                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
--  Let us list the factors of the first seven triangle numbers:
--
--                  1: 1
--                  3: 1,3
--                  6: 1,2,3,6
--                 10: 1,2,5,10
--                 15: 1,3,5,15
--                 21: 1,3,7,21
--                 28: 1,2,4,7,14,28
--
--  We can see that 28 is the first triangle number to have over five
--  divisors.
--
--  What is the value of the first triangle number to have over five hundred
--  divisors?
--
-------------------------------------------------------------------------------

with Euler_Tools; use Euler_Tools;

package body P0012_Highly_Divisible_Triangular_Number is

   overriding function Answer
     (Problem : in out Problem_Type; Notes : in out Unbounded_String)
      return String
   is
      Number   : Integer_Type := 8;
      Divisors : Set_Type;
      Answer   : Integer_Type;
   begin

      loop
         Answer   := Sum_Sequence (Number);
         Divisors := All_Divisors (Answer);

         exit when Length (Divisors) > 500;
         Divisors.Clear;
         Number := @ + 1;
      end loop;

      Notes :=
        To_Unbounded_String
          ("It has" & Natural'Image (Length (Divisors)) & " divisors.");

      return To_String (Answer);
   end Answer;

end P0012_Highly_Divisible_Triangular_Number;
