#     _    _ _
#    / \  | (_) ___ ___
#   / _ \ | | |/ __/ _ \         Adventures for Learning and
#  / ___ \| | | (_|  __/         Inspiring Coding Excellence
# /_/   \_\_|_|\___\___|
#  ___ ___  ___     _ ___ ___ _____   ___ _   _ _    ___ ___
# | _ \ _ \/ _ \ _ | | __/ __|_   _| | __| | | | |  | __| _ \
# |  _/   / (_) | || | _| (__  | |   | _|| |_| | |__| _||   /
# |_| |_|_\\___/ \__/|___\___| |_|   |___|\___/|____|___|_|_\
#
# —————————————————————————————————————————————————————————————————————————————
#
# Welcome to our registration process! To participate in Alice/Project Euler,
# please follow these instructions carefully:
#
#  1. Fill in your personal data: Please enter your name and email address in
#     the designated fields.
#
#  2. Fill in participant data: Please enter your user name (must be unique),
#     Git repository URL, and branch name in the designated fields. This
#     information is essential for us to review your work and ensure that you
#     are eligible to participate.
#
#  3. Create a pull request: Once you have filled in all the required
#     information, please create a pull request to the designated repository
#     to activate your registration. We will review your pull request and get
#     back to you within a week.
#
# Note: Make sure to double-check all the information you have entered before
#       creating a pull request. Inaccurate or incomplete information may
#       delay the review process or disqualify you from participating.
#
# Thank you for your interest in Alice/Project Euler, and we look forward to
# reviewing your work!
#
# —————————————————————————————————————————————————————————————————————————————
#

[[user]]

# personal data
name = "Francesc Rocher"
email = "francesc.rocher@gmail.com"
organization = "Alice project"

# participant data
usr = "rocher" # MUST BE UNIQUE
repository.url = "git@github.com:rocher/Alice_Project_Euler_Rocher"
repository.branch = "main"


# Template

# [[user]]
# # personal data
# name = ""
# email = ""
# orgranization = ""
#
# # participant data
# usr = ""
# repository.url = ""
# repository.branch = ""
